services:
  user-service:
    build:
      context: ./src/backend/user-service
    container_name: user-service
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - db
    environment:
      - MONGODB_URI=mongodb://db:27017/sports_management
      - JWT_SECRET=ecabf4c7e38a5bb1627e85c58ec13d03c40bbd20c89a911cfd6bfac747465a95

  facility-service:
    build:
      context: ./src/backend/facility-service
    container_name: facility-service
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - db
    environment:
      - MONGODB_URI=mongodb://db:27017/sports_management
      - JWT_SECRET=ecabf4c7e38a5bb1627e85c58ec13d03c40bbd20c89a911cfd6bfac747465a95

  db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongodb-data:/data/db

  api-gateway:
    image: nginx:latest
    container_name: api-gateway
    ports:
      - "80:80"
    volumes:
      - "./src/backend/gateway/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - app-network
    depends_on:
      - user-service
      - facility-service

  frontend:
    build:
      context: ./src/frontend
    container_name: frontend
    ports:
      - "8080:80" 
    networks:
      - app-network
    depends_on:
      - api-gateway

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
